sources:
    # GraphQL schema
  - name: resolvers
    handler:
        graphql:
            endpoint: http://localhost:3000/graphql
    # GraphQL schema
  - name: hasura
    handler:
        graphql:
            endpoint: http://localhost:8080/v1/graphql
            headers:
                X-Hasura-Admin-Secret: keyboardcat
    # OpenApi schema
  - name: openapi
    handler:
        openapi:
            source: ./swagger-example.yaml
